[functions.create-razorpay-order]
enabled = true
verify_jwt = false
import_map = "./functions/create-razorpay-order/deno.json"
entrypoint = "./functions/create-razorpay-order/index.ts"

[functions.razorpay-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/razorpay-webhook/deno.json"
entrypoint = "./functions/razorpay-webhook/index.ts"
